#!/bin/bash

HARDWARE="/Users/amorrison/Arduino.app/Contents/Java/hardware"
HEXFILE="client.hex"
AVRDUDE="$HARDWARE/tools/avr/bin/avrdude"
AVRDUDE_CONF="$HARDWARE/tools/avr/etc/avrdude.conf"

fatal(){
	echo $1
	exit 1
}
usage(){
	echo "Usage: $0 \$/PATH/TO/ARDUINO/USB/MODEM"
	exit 1
}
[[ -e $HEXFILE ]] || fatal "$HEXFILE doesn't exist!"
[[ "x$1" = "x" ]] && usage $0
[[ -e $1 ]] || fatal "$1 doesn't exist!"

[[ -e $AVRDUDE ]] || fatal "AVRDUDE ($AVRDUDE) not found!"
[[ -e $AVRDUDE_CONF ]] || fatal "config ($AVRDUDE_CONF) not found!"

$AVRDUDE -C$AVRDUDE_CONF -v -patmega2560 -cwiring -P$1 -b115200 -D -Uflash:w:$HEXFILE:i
