#ifndef TOWER_PIN_DEFINES_H
#define TOWER_PIN_DEFINES_H

#define PIN_REMOTEFILL_POWER 28
#define PIN_REMOTEFILL_SELECT 29

#define PIN_REMOTEVENT_POWER 26
#define PIN_REMOTEVENT_SELECT 25

#define PIN_LINACTUATOR_POWER 24
#define PIN_LINACTUATOR_SELECT 27

#define PIN_IGNITION_POWER 22
#define PIN_IGNITION_SELECT 23

//daq pins
#define PIN_DAQ_MASS XX
#define PIN_DAQ_PRESSURE1 XX
#define PIN_DAQ_PRESSURE2 XX
//current sensor pins
#define PIN_CURRENT_IGNITION_PRI XX
#define PIN_CURRENT_IGNITION_SEC XX
#define PIN_CURRENT_REMOTEFILL_OPN XX
#define PIN_CURRENT_REMOTEFILL_CLS XX
#define PIN_CURRENT_REMOTEVENT_OPN XX
#define PIN_CURRENT_REMOTEVENT_CLS XX
#define PIN_CURRENT_LINAC_EXT XX
#define PIN_CURRENT_LINAC_RET XX
//limit switch pins
#define PIN_LIMITSW_REMOTEFILL_OPN XX
#define PIN_LIMITSW_REMOTEFILL_CLS XX
#define PIN_LIMITSW_REMOTEVENT_OPN XX
#define PIN_LIMITSW_REMOTEVENT_CLS XX
#define PIN_LIMITSW_LINAC_EXT XX
#define PIN_LIMITSW_LINAC_RET XX

#endif //ifndef TOWER_PIN_DEFINES_H
