#ifndef TOWER_PIN_DEFINES_H
#define TOWER_PIN_DEFINES_H

#define PIN_REMOTEFILL_POWER 22
#define PIN_REMOTEFILL_SELECT 23

#define PIN_REMOTEVENT_POWER 25
#define PIN_REMOTEVENT_SELECT 24

#define PIN_LINACTUATOR_POWER 26
#define PIN_LINACTUATOR_SELECT 27

#define PIN_IGNITION_POWER 28
#define PIN_IGNITION_SELECT 29

//daq pins
#define PIN_DAQ_MASS XX
#define PIN_DAQ_PRESSURE1 XX
#define PIN_DAQ_PRESSURE2 XX
//current sensor pins
#define PIN_CURRENT_IGNITION_PRI 8
#define PIN_CURRENT_IGNITION_SEC 9
#define PIN_CURRENT_REMOTEFILL_OPN 15
#define PIN_CURRENT_REMOTEFILL_CLS 14
#define PIN_CURRENT_REMOTEVENT_OPN 13
#define PIN_CURRENT_REMOTEVENT_CLS 12
#define PIN_CURRENT_LINAC_EXT 10
#define PIN_CURRENT_LINAC_RET 11
//limit switch pins
#define PIN_LIMITSW_REMOTEFILL_OPN 30
#define PIN_LIMITSW_REMOTEFILL_CLS 31
#define PIN_LIMITSW_REMOTEVENT_OPN 32
#define PIN_LIMITSW_REMOTEVENT_CLS 33
#define PIN_LIMITSW_LINAC_EXT 35
#define PIN_LIMITSW_LINAC_RET 34

#endif //ifndef TOWER_PIN_DEFINES_H
